- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    name: create VM
    vmware_guest:
    hostname: "{{ vcenter_ip }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    cluster: "{{ vcenter_cluster }}"
    folder: /testvms
    name: testvm_2
    state: poweredon
    template: Linux_temp
    disk:
    - size_gb: 10
      type: thin
      datastore: "{{ vcenter_datastore }}"
    hardware:
      memory_mb: 512
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: False
      version: 12 # Hardware version of virtual machine
    networks:
    - name: VM Network
      mac: aa:bb:dd:aa:00:14
    wait_for_ip_address: no
  
