- name: convert hosts from csv
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    csvfile: "{{ lookup('file', 'vars/hosts.csv') }}"
  tasks:
    - name: Parse CSV To YAML
      template:
        src: "./iterate_csv.j2"
        dest: "./iterate_hosts.yml"
      run_once: true
    - name: create VM
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_dc }}"
        folder: /testvms
        name: testvm_2
        state: poweredon
        template: Linux_temp
        disk:
        - size_gb: 10
          type: thin
          datastore: "{{ vcenter_datastore }}"
        hardware:
          memory_mb: 512
          num_cpus: 1
          num_cpu_cores_per_socket: 1
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
          version: 12 # Hardware version of virtual machine
        networks:
        - name: VM Network
          mac: aa:bb:dd:aa:00:14
        wait_for_ip_address: no
