- name: convert hosts from csv
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    csvfile: "{{ lookup('file', '../server_vmparams.csv') }}"
  tasks:
    - name: Parse CSV To YAML
      template:
        src: "./iterate_csv.j2"
        dest: "../iterate_hosts.yml"
      run_once: true
    - name: parse csv for PG
      template:
        src: "./iterate_pg.j2"
        dest: "../iterate_vlan.yml"
      run_once: true
