- name: create PG in DVS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    DVS_PG_name: 1009_VLAN_temp
    DVS_PG_vlanid: 1009
  tasks:
    - name: check file
      stat: 
        path: ../iterate_vlan.yml
      register: stat_result

    - name: load CSV To YAML
      include_vars:
        file: ../iterate_vlan.yml
        name: vlan_pgs
      when: stat_result.stat.exists == true 
      
    - name: Create Management portgroup
      local_action:
        module: vmware_dvs_portgroup
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        portgroup_name: "{{ item.vlan_name }}"
        switch_name: "vDS_NEW"
        vlan_id: "{{ item.vlan_id }}"
        num_ports: 10
        portgroup_type: earlyBinding
        state: present
      loop: "{{ vlan_pgs.vlanpgs }}"
