- name: modify existing VM
  hosts: localhost
  connection: local
  gather_facts: yes
  become: false
  vars:
    vcenter_ip: vcsa.mcit.local
    vcenter_username: cfadmin@vsphere.local
    vcenter_password: Redhat@123
    vcenter_cluster: CF_POC
    vcenter_dc: MCIT_DC
    folder: /cf
  tasks:
    - name: modify VM
      vmware_guest:
        state: reconfigured
        name: "{{ vm_name }}"
        hardware:
          memory_mb: "{{ new_memory }}"
          num_cpus:  "{{ new_cpu }}"
        network:
        - name: "{{ new_vm_network }}"
    
